### ISSUE TITLE
Drop Rails 4 support?

### ISSUE THREAD

**Issue by natebird** [devise-security/devise-security#1]
I'm wondering if we really need to support older versions of Ruby and older versions of Rails? Since this is a fork of the old gem there may be some advantages to cleaning up and supporting just the newer versions. Thoughts?

**Comment by olbrich** [comment]
A reasonable policy might be to maintain support for all ruby versions that are officially supported (>= 2.2.7) and Rails ( >= 4.2).  It often takes a while for people to update applications and it would be unfortunate if they could not update and get security fixes because they aren't running the latest and greatest.

**Comment by oniofchaos** [comment]
One way I've seen that could work is using major versions to indicate support levels. For example, version 8.x is for Rails 4 and 9.x is for Rails 5, with security updates but not new features making it to 8.x.
