### ISSUE TITLE
:secure_validatable enforces email uniqueness.(is there a way to bypass it)

### ISSUE THREAD

**Issue by upendra-datt-roostify** [devise-security/devise-security#138]
I am trying to use: secure_validatable module in my system for password policy only but it also includes checks for email like email uniqueness. Is there any way we can bypass email uniqueness check here. 

We explicitly did not want to use email uniqueness hence we did not use the devise validatable module. and devise-security gem checks if validatable is not used they start enforcing email_uniqueness.

Is there any way around it. if so, can someone help me with this?

**Comment by oniofchaos** [comment]
https://github.com/devise-security/devise-security/blob/596696d2df4eada853ec72c32018449252aacad0/lib/devise-security/models/secure_validatable.rb#L44

The way I'm reading the code, the email validation check only occurs if `email_changed?` is true. You could try adding a method called `email_changed?` in your model that returns false, so that this never fires.

Alternatively, you could add a configuration option for this as part of https://github.com/devise-security/devise-security/blob/master/README.md#configuration

**Comment by upendra-datt-roostify** [comment]
It worked! Thanks a lot @oniofchaos for the help! :)
